#!/usr/bin/env bash
# Scholar-Skill Setup Script
# Run once after cloning: bash setup.sh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env"

echo "═══════════════════════════════════════════════════"
echo "  Scholar-Skill Setup"
echo "═══════════════════════════════════════════════════"
echo ""

# ── 1. Create symlinks if needed ──────────────────────────────────
echo "▸ Checking symlinks..."

if [ -L "$SCRIPT_DIR/skills" ]; then
  echo "  ✓ skills/ symlink exists"
elif [ -d "$SCRIPT_DIR/.claude/skills" ]; then
  rm -rf "$SCRIPT_DIR/skills"
  ln -sf .claude/skills "$SCRIPT_DIR/skills"
  echo "  ✓ Created skills/ → .claude/skills/"
else
  echo "  ⚠ .claude/skills/ not found — skipping symlink"
fi

if [ -L "$SCRIPT_DIR/agents" ]; then
  echo "  ✓ agents/ symlink exists"
elif [ -d "$SCRIPT_DIR/.claude/agents" ]; then
  rm -rf "$SCRIPT_DIR/agents"
  ln -sf .claude/agents "$SCRIPT_DIR/agents"
  echo "  ✓ Created agents/ → .claude/agents/"
else
  echo "  ⚠ .claude/agents/ not found — skipping symlink"
fi

echo ""

# ── 2. Auto-detect Zotero ─────────────────────────────────────────
echo "▸ Looking for Zotero library..."

ZOTERO_DIR=""
for candidate in \
  "$HOME/Zotero" \
  "$HOME/Documents/Zotero" \
  "$HOME/snap/zotero-snap/common/Zotero" \
  "$HOME/Library/CloudStorage/"*/zotero \
  "$HOME/Library/CloudStorage/"*/Zotero \
  "$HOME/Google Drive/zotero" \
  "$HOME/Google Drive/Zotero"; do
  if [ -f "$candidate/zotero.sqlite" ] 2>/dev/null || [ -f "$candidate/zotero.sqlite.bak" ] 2>/dev/null; then
    ZOTERO_DIR="$candidate"
    break
  fi
done

if [ -n "$ZOTERO_DIR" ]; then
  echo "  ✓ Found Zotero at: $ZOTERO_DIR"
else
  echo "  ⚠ Zotero not auto-detected."
  read -rp "  Enter Zotero library path (or press Enter to skip): " user_zotero
  if [ -n "$user_zotero" ] && [ -d "$user_zotero" ]; then
    ZOTERO_DIR="$user_zotero"
    echo "  ✓ Using: $ZOTERO_DIR"
  else
    echo "  → Skipping Zotero setup. You can set SCHOLAR_ZOTERO_DIR in .env later."
  fi
fi

echo ""

# ── 3. Optional: BibTeX / EndNote ─────────────────────────────────
echo "▸ Optional reference managers..."

BIB_PATH=""
read -rp "  Path to a .bib file (or press Enter to skip): " user_bib
if [ -n "$user_bib" ] && [ -f "$user_bib" ]; then
  BIB_PATH="$user_bib"
  echo "  ✓ BibTeX: $BIB_PATH"
elif [ -n "$user_bib" ]; then
  echo "  ⚠ File not found: $user_bib — skipping"
fi

ENDNOTE_XML=""
read -rp "  Path to an EndNote XML export (or press Enter to skip): " user_endnote
if [ -n "$user_endnote" ] && [ -f "$user_endnote" ]; then
  ENDNOTE_XML="$user_endnote"
  echo "  ✓ EndNote XML: $ENDNOTE_XML"
elif [ -n "$user_endnote" ]; then
  echo "  ⚠ File not found: $user_endnote — skipping"
fi

CROSSREF_EMAIL=""
read -rp "  CrossRef/OpenAlex polite pool email (or press Enter to skip): " user_email
if [ -n "$user_email" ]; then
  CROSSREF_EMAIL="$user_email"
  echo "  ✓ CrossRef email: $CROSSREF_EMAIL"
fi

echo ""

# ── 3b. Knowledge graph directory ────────────────────────────────
echo "▸ Knowledge graph setup..."

KNOWLEDGE_DIR="${HOME}/.claude/scholar-knowledge"
read -rp "  Knowledge graph directory [$KNOWLEDGE_DIR]: " user_kg_dir
if [ -n "$user_kg_dir" ]; then
  KNOWLEDGE_DIR="$user_kg_dir"
fi
mkdir -p "$KNOWLEDGE_DIR"
echo "  ✓ Knowledge graph: $KNOWLEDGE_DIR"

echo ""

# ── 4. Write .env file ───────────────────────────────────────────
echo "▸ Writing .env file..."

cat > "$ENV_FILE" << ENVEOF
# Scholar-Skill Configuration
# Generated by setup.sh on $(date +%Y-%m-%d)
# Edit paths below to match your system.

# Scholar-skill installation directory (REQUIRED for cross-project use)
SCHOLAR_SKILL_DIR="${SCRIPT_DIR}"

# Zotero library directory (containing zotero.sqlite)
SCHOLAR_ZOTERO_DIR="${ZOTERO_DIR}"

# BibTeX .bib file path (optional)
SCHOLAR_BIB_PATH="${BIB_PATH}"

# EndNote XML export path (optional)
SCHOLAR_ENDNOTE_XML="${ENDNOTE_XML}"

# CrossRef / OpenAlex polite pool email (optional but recommended)
SCHOLAR_CROSSREF_EMAIL="${CROSSREF_EMAIL}"

# Knowledge graph directory (user-scoped, cross-project)
# Default: ~/.claude/scholar-knowledge
SCHOLAR_KNOWLEDGE_DIR="${KNOWLEDGE_DIR}"
ENVEOF

echo "  ✓ Wrote $ENV_FILE"
echo ""

# ── 5. Install as personal skills (global access) ────────────────
echo "▸ Installing as personal Claude Code skills..."

PERSONAL_SKILLS_DIR="$HOME/.claude/skills"
PERSONAL_AGENTS_DIR="$HOME/.claude/agents"

mkdir -p "$PERSONAL_SKILLS_DIR"
mkdir -p "$PERSONAL_AGENTS_DIR"

# Symlink _shared/ protocol directory
shared_src="$SCRIPT_DIR/.claude/skills/_shared"
shared_target="$PERSONAL_SKILLS_DIR/_shared"
if [ -d "$shared_src" ]; then
  if [ -L "$shared_target" ] || [ -d "$shared_target" ]; then
    echo "  ✓ _shared (already installed)"
  else
    ln -s "$shared_src" "$shared_target"
    echo "  ✓ _shared (installed)"
  fi
fi

# Symlink each skill directory
skill_count=0
for skill_dir in "$SCRIPT_DIR/.claude/skills"/scholar-*/ "$SCRIPT_DIR/.claude/skills"/sync-docs/; do
  [ -d "$skill_dir" ] || continue
  name="$(basename "$skill_dir")"
  target="$PERSONAL_SKILLS_DIR/$name"
  if [ -L "$target" ] || [ -d "$target" ]; then
    echo "  ✓ $name (already installed)"
  else
    ln -s "$skill_dir" "$target"
    echo "  ✓ $name (installed)"
  fi
  skill_count=$((skill_count + 1))
done

# Symlink each agent file
agent_count=0
for agent_file in "$SCRIPT_DIR/.claude/agents"/peer-reviewer-*.md; do
  [ -f "$agent_file" ] || continue
  name="$(basename "$agent_file")"
  target="$PERSONAL_AGENTS_DIR/$name"
  if [ -L "$target" ] || [ -f "$target" ]; then
    echo "  ✓ $name (already installed)"
  else
    ln -s "$agent_file" "$target"
    echo "  ✓ $name (installed)"
  fi
  agent_count=$((agent_count + 1))
done

echo "  → $skill_count skills, $agent_count agents installed to ~/.claude/"
echo "  → Skills are now available in ALL projects via Claude Code"
echo ""

# ── 6. Add SCHOLAR_SKILL_DIR to shell profile ────────────────────
echo "▸ Setting up shell environment..."

EXPORT_LINE="export SCHOLAR_SKILL_DIR=\"$SCRIPT_DIR\""
SHELL_RC=""

if [ -n "${ZSH_VERSION:-}" ] || [ "$(basename "${SHELL:-}")" = "zsh" ]; then
  SHELL_RC="$HOME/.zshrc"
elif [ -n "${BASH_VERSION:-}" ] || [ "$(basename "${SHELL:-}")" = "bash" ]; then
  SHELL_RC="$HOME/.bashrc"
  [ -f "$HOME/.bash_profile" ] && SHELL_RC="$HOME/.bash_profile"
fi

if [ -n "$SHELL_RC" ]; then
  if grep -qF "SCHOLAR_SKILL_DIR" "$SHELL_RC" 2>/dev/null; then
    echo "  ✓ SCHOLAR_SKILL_DIR already in $SHELL_RC"
  else
    read -rp "  Add SCHOLAR_SKILL_DIR to $SHELL_RC? [Y/n] " add_to_rc
    add_to_rc="${add_to_rc:-Y}"
    if [[ "$add_to_rc" =~ ^[Yy] ]]; then
      echo "" >> "$SHELL_RC"
      echo "# Scholar-Skill plugin directory" >> "$SHELL_RC"
      echo "$EXPORT_LINE" >> "$SHELL_RC"
      echo "  ✓ Added to $SHELL_RC"
      echo "  → Run: source $SHELL_RC   (or open a new terminal)"
    else
      echo "  → Skipped. Add manually if needed:"
      echo "    $EXPORT_LINE"
    fi
  fi
else
  echo "  ⚠ Could not detect shell profile. Add manually:"
  echo "    $EXPORT_LINE"
fi

echo ""

# ── 7. Summary ────────────────────────────────────────────────────
echo "═══════════════════════════════════════════════════"
echo "  Setup Complete"
echo "═══════════════════════════════════════════════════"
echo ""
echo "  SCHOLAR_SKILL_DIR=$SCRIPT_DIR"
[ -n "$ZOTERO_DIR" ] && echo "  Zotero:     $ZOTERO_DIR"
[ -n "$BIB_PATH" ]   && echo "  BibTeX:     $BIB_PATH"
[ -n "$ENDNOTE_XML" ] && echo "  EndNote:    $ENDNOTE_XML"
echo ""
echo "  Next steps:"
echo "  1. Source your shell profile or open a new terminal"
echo "  2. Try from any project: /scholar-idea \"your research question\""
echo ""
